front:
    resource: "@FrontBundle/Resources/config/routing.yml"
    prefix:   /

app:
    resource: "@AppBundle/Controller/"
    type:     annotation

fos_user:
    resource: "@FOSUserBundle/Resources/config/routing/all.xml"

fos_user_registration_confirmed:
    pattern: /Profile
    defaults: { _controller: FrontBundle:Profile:profile }
    requirements:
        _method: POST|GET


fos_delete_User:
    path:     /delete/{id}
    defaults: { _controller: AppBundle:Default:delete }
