<?php

namespace FrontBundle\Repository;

/**
 * GouvernoratsRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class GouvernoratsRepository extends \Doctrine\ORM\EntityRepository
{
}
